In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import zscore

In [3]:
path = 'C:/Code/StudentPerformance_Pre/student-por.csv'

In [4]:
# 调整显示最大行数，列数，和列宽

pd.set_option('display.max_rows', 100)

pd.set_option('display.max_columns', 50)

pd.set_option('display.max_colwidth', 100)

In [5]:
data = pd.read_csv(path)

In [6]:
data.head(20)

   school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3
0   GP;"F";18;"U";"GT3";"A";4;4;"at_home";"teacher";"course";"mother";2;2;0;"yes";"no";"no";"no";"ye...
1   GP;"F";17;"U";"GT3";"T";1;1;"at_home";"other";"course";"father";1;2;0;"no";"yes";"no";"no";"no";...
2   GP;"F";15;"U";"LE3";"T";1;1;"at_home";"other";"other";"mother";1;2;0;"yes";"no";"no";"no";"yes";...
3   GP;"F";15;"U";"GT3";"T";4;2;"health";"services";"home";"mother";1;3;0;"no";"yes";"no";"yes";"yes...
4   GP;"F";16;"U";"GT3";"T";3;3;"other";"other";"home";"father";1;2;0;"no";"yes";"no";"no";"yes";"ye...
5   GP;"M";16;"U";"LE3";"T";4;3;"services";"other";"reputation";"mother";1;2;0;"no";"yes";"no";"yes"...
6   GP;"M";16;"U";"LE3";"T";2;2;"other";"other";"home";"mother";1;2;0;"no";"no";"no";"no";"yes";"yes...
7   GP;"F";17;"U";"GT3";"A";4;4;"other";"teacher";"home";"mother";2;2;0;"yes";"yes";"no";"no";"yes";...
8   GP;"M";15;"U";"LE3";"A";3;2;"services";"other";"home";"mother";1;2;0;"no";"yes";"no";"no";"yes";...
9   GP;"M";15;"U";"GT3";"T";3;4;"other";"other";"home";"mother";1;2;0;"no";"yes";"no";"yes";"yes";"y...
10  GP;"F";15;"U";"GT3";"T";4;4;"teacher";"health";"reputation";"mother";1;2;0;"no";"yes";"no";"no";...
11  GP;"F";15;"U";"GT3";"T";2;1;"services";"other";"reputation";"father";3;3;0;"no";"yes";"no";"yes"...
12  GP;"M";15;"U";"LE3";"T";4;4;"health";"services";"course";"father";1;1;0;"no";"yes";"no";"yes";"y...
13  GP;"M";15;"U";"GT3";"T";4;3;"teacher";"other";"course";"mother";2;2;0;"no";"yes";"no";"no";"yes"...
14  GP;"M";15;"U";"GT3";"A";2;2;"other";"other";"home";"other";1;3;0;"no";"yes";"no";"no";"yes";"yes...
15  GP;"F";16;"U";"GT3";"T";4;4;"health";"other";"home";"mother";1;1;0;"no";"yes";"no";"no";"yes";"y...
16  GP;"F";16;"U";"GT3";"T";4;4;"services";"services";"reputation";"mother";1;3;0;"no";"yes";"no";"y...
17  GP;"F";16;"U";"GT3";"T";3;3;"other";"other";"reputation";"mother";3;2;0;"yes";"yes";"no";"yes";"...
18  GP;"M";17;"U";"GT3";"T";3;2;"services";"services";"course";"mother";1;1;3;"no";"yes";"yes";"yes"...
19  GP;"M";16;"U";"LE3";"T";4;3;"health";"other";"home";"father";1;1;0;"no";"no";"no";"yes";"yes";"y...

In [7]:
len(data)

649

In [8]:
len(data.columns)

1

In [9]:
data = pd.read_csv(path, delimiter=';')

In [10]:
data.head(20)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother,2,2,0,yes,no,no,no,yes,yes,no,no,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father,1,2,0,no,yes,no,no,no,yes,yes,no,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother,1,2,0,yes,no,no,no,yes,yes,yes,no,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother,1,3,0,no,yes,no,yes,yes,yes,yes,yes,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,home,father,1,2,0,no,yes,no,no,yes,yes,no,no,4,3,2,1,2,5,0,11,13,13
5,GP,M,16,U,LE3,T,4,3,services,other,reputation,mother,1,2,0,no,yes,no,yes,yes,yes,yes,no,5,4,2,1,2,5,6,12,12,13
6,GP,M,16,U,LE3,T,2,2,other,other,home,mother,1,2,0,no,no,no,no,yes,yes,yes,no,4,4,4,1,1,3,0,13,12,13
7,GP,F,17,U,GT3,A,4,4,other,teacher,home,mother,2,2,0,yes,yes,no,no,yes,yes,no,no,4,1,4,1,1,1,2,10,13,13
8,GP,M,15,U,LE3,A,3,2,services,other,home,mother,1,2,0,no,yes,no,no,yes,yes,yes,no,4,2,2,1,1,1,0,15,16,17
9,GP,M,15,U,GT3,T,3,4,other,other,home,mother,1,2,0,no,yes,no,yes,yes,yes,yes,no,5,5,1,1,1,5,0,12,12,13
10,GP,F,15,U,GT3,T,4,4,teacher,health,reputation,mother,1,2,0,no,yes,no,no,yes,yes,yes,no,3,3,3,1,2,2,2,14,14,14
11,GP,F,15,U,GT3,T,2,1,services,other,reputation,father,3,3,0,no,yes,no,yes,yes,yes,yes,no,5,2,2,1,1,4,0,10,12,13
12,GP,M,15,U,LE3,T,4,4,health,services,course,father,1,1,0,no,yes,no,yes,yes,yes,yes,no,4,3,3,1,3,5,0,12,13,12
13,GP,M,15,U,GT3,T,4,3,teacher,other,course,mother,2,2,0,no,yes,no,no,yes,yes,yes,no,5,4,3,1,2,3,0,12,12,13
14,GP,M,15,U,GT3,A,2,2,other,other,home,other,1,3,0,no,yes,no,no,yes,yes,yes,yes,4,5,2,1,1,3,0,14,14,15
15,GP,F,16,U,GT3,T,4,4,health,other,home,mother,1,1,0,no,yes,no,no,yes,yes,yes,no,4,4,4,1,2,2,6,17,17,17
16,GP,F,16,U,GT3,T,4,4,services,services,reputation,mother,1,3,0,no,yes,no,yes,yes,yes,yes,no,3,2,3,1,2,2,10,13,13,14
17,GP,F,16,U,GT3,T,3,3,other,other,reputation,mother,3,2,0,yes,yes,no,yes,yes,yes,no,no,5,3,2,1,1,4,2,13,14,14
18,GP,M,17,U,GT3,T,3,2,services,services,course,mother,1,1,3,no,yes,yes,yes,yes,yes,yes,no,5,5,5,2,4,5,2,8,8,7
19,GP,M,16,U,LE3,T,4,3,health,other,home,father,1,1,0,no,no,no,yes,yes,yes,yes,no,3,1,3,1,3,5,6,12,12,12

In [11]:
df = data
# 查看数据集的列类型
print("数据集的每列类型：")
print(df.dtypes)

# 获取分类数据类型的列
categorical_columns = df.select_dtypes(include=['object', 'category']).columns
print("\n分类数据类型的特征：", categorical_columns)

# 统计分类特征的数量
num_categorical_features = len(categorical_columns)
print("\n分类特征的数量：", num_categorical_features)

# 查看数据集的总特征数量
num_features = df.shape[1]
print("\n数据集总共有", num_features, "个特征")

数据集的每列类型：
school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64
dtype: object

分类数据类型的特征： Index(['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob',
       'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities',
       'nursery', 'higher', 'internet', 'romantic'],
      dtype='object')

分类特征的数量： 17

数据集总共有 33 个特征

In [12]:

# 统计每个分类特征的数量和百分比
summary = {}

# 遍历每个分类特征
for column in df.select_dtypes(include=['object', 'int64']).columns:
    counts = df[column].value_counts()  # 计算每个标签的数量
    percentages = df[column].value_counts(normalize=True) * 100  # 计算每个标签的百分比
    
    # 格式化输出每个特征的统计数据
    summary[column] = pd.DataFrame({
        'n': counts,
        'n (%)': counts.astype(str) + ' (' + percentages.round(2).astype(str) + '%)'
    })

# 输出每个特征的统计结果
for column, stats in summary.items():
    print(f"\n统计 {column} 列:")
    print(stats)

统计 school 列:
          n         n (%)
school
GP      423  423 (65.18%)
MS      226  226 (34.82%)

统计 sex 列:
       n         n (%)
sex
F    383  383 (59.01%)
M    266  266 (40.99%)

统计 age 列:
       n         n (%)
age
17   179  179 (27.58%)
16   177  177 (27.27%)
18   140  140 (21.57%)
15   112  112 (17.26%)
19    32    32 (4.93%)
20     6     6 (0.92%)
21     2     2 (0.31%)
22     1     1 (0.15%)

统计 address 列:
           n         n (%)
address
U        452  452 (69.65%)
R        197  197 (30.35%)

统计 famsize 列:
           n         n (%)
famsize
GT3      457  457 (70.42%)
LE3      192  192 (29.58%)

统计 Pstatus 列:
           n         n (%)
Pstatus
T        569  569 (87.67%)
A         80   80 (12.33%)

统计 Medu 列:
        n         n (%)
Medu
2     186  186 (28.66%)
4     175  175 (26.96%)
1     143  143 (22.03%)
3     139  139 (21.42%)
0       6     6 (0.92%)

统计 Fedu 列:
        n         n (%)
Fedu
2     209   209 (32.2%)
1     174  174 (26.81%)
3     131  131 (20.18%)
4     128  128 (19.72%)
0       7     7 (1.08%)

统计 Mjob 列:
            n         n (%)
Mjob
other     258  258 (39.75%)
services  136  136 (20.96%)
at_home   135   135 (20.8%)
teacher    72   72 (11.09%)
health     48     48 (7.4%)

统计 Fjob 列:
            n         n (%)
Fjob
other     367  367 (56.55%)
services  181  181 (27.89%)
at_home    42    42 (6.47%)
teacher    36    36 (5.55%)
health     23    23 (3.54%)

统计 reason 列:
              n         n (%)
reason
course      285  285 (43.91%)
home        149  149 (22.96%)
reputation  143  143 (22.03%)
other        72   72 (11.09%)

统计 guardian 列:
            n         n (%)
guardian
mother    455  455 (70.11%)
father    153  153 (23.57%)
other      41    41 (6.32%)

统计 traveltime 列:
              n         n (%)
traveltime
1           366  366 (56.39%)
2           213  213 (32.82%)
3            54    54 (8.32%)
4            16    16 (2.47%)

统计 studytime 列:
             n         n (%)
studytime
2          305   305 (47.0%)
1          212  212 (32.67%)
3           97   97 (14.95%)
4           35    35 (5.39%)

统计 failures 列:
            n         n (%)
failures
0         549  549 (84.59%)
1          70   70 (10.79%)
2          16    16 (2.47%)
3          14    14 (2.16%)

统计 schoolsup 列:
             n         n (%)
schoolsup
no         581  581 (89.52%)
yes         68   68 (10.48%)

统计 famsup 列:
          n         n (%)
famsup
yes     398  398 (61.33%)
no      251  251 (38.67%)

统计 paid 列:
        n         n (%)
paid
no    610  610 (93.99%)
yes    39    39 (6.01%)

统计 activities 列:
              n         n (%)
activities
no          334  334 (51.46%)
yes         315  315 (48.54%)

统计 nursery 列:
           n         n (%)
nursery
yes      521  521 (80.28%)
no       128  128 (19.72%)

统计 higher 列:
          n         n (%)
higher
yes     580  580 (89.37%)
no       69   69 (10.63%)

统计 internet 列:
            n         n (%)
internet
yes       498  498 (76.73%)
no        151  151 (23.27%)

统计 romantic 列:
            n         n (%)
romantic
no        410  410 (63.17%)
yes       239  239 (36.83%)

统计 famrel 列:
          n         n (%)
famrel
4       317  317 (48.84%)
5       180  180 (27.73%)
3       101  101 (15.56%)
2        29    29 (4.47%)
1        22    22 (3.39%)

统计 freetime 列:
            n         n (%)
freetime
3         251  251 (38.67%)
4         178  178 (27.43%)
2         107  107 (16.49%)
5          68   68 (10.48%)
1          45    45 (6.93%)

统计 goout 列:
         n         n (%)
goout
3      205  205 (31.59%)
2      145  145 (22.34%)
4      141  141 (21.73%)
5      110  110 (16.95%)
1       48     48 (7.4%)

统计 Dalc 列:
        n         n (%)
Dalc
1     451  451 (69.49%)
2     121  121 (18.64%)
3      43    43 (6.63%)
5      17    17 (2.62%)
4      17    17 (2.62%)

统计 Walc 列:
        n         n (%)
Walc
1     247  247 (38.06%)
2     150  150 (23.11%)
3     120  120 (18.49%)
4      87   87 (13.41%)
5      45    45 (6.93%)

统计 health 列:
          n         n (%)
health
5       249  249 (38.37%)
3       124  124 (19.11%)
4       108  108 (16.64%)
1        90   90 (13.87%)
2        78   78 (12.02%)

统计 absences 列:
            n         n (%)
absences
0         244   244 (37.6%)
2         110  110 (16.95%)
4          93   93 (14.33%)
6          49    49 (7.55%)
8          42    42 (6.47%)
10         21    21 (3.24%)
1          12    12 (1.85%)
12         12    12 (1.85%)
5          12    12 (1.85%)
16         10    10 (1.54%)
14          8     8 (1.23%)
9           7     7 (1.08%)
3           7     7 (1.08%)
11          5     5 (0.77%)
18          3     3 (0.46%)
7           3     3 (0.46%)
21          2     2 (0.31%)
15          2     2 (0.31%)
22          2     2 (0.31%)
30          1     1 (0.15%)
26          1     1 (0.15%)
24          1     1 (0.15%)
13          1     1 (0.15%)
32          1     1 (0.15%)

统计 G1 列:
     n        n (%)
G1
10  95  95 (14.64%)
11  91  91 (14.02%)
12  82  82 (12.63%)
13  72  72 (11.09%)
14  71  71 (10.94%)
9   65  65 (10.02%)
8   42   42 (6.47%)
15  35   35 (5.39%)
7   33   33 (5.08%)
16  22   22 (3.39%)
17  16   16 (2.47%)
6    9    9 (1.39%)
18   7    7 (1.08%)
5    5    5 (0.77%)
4    2    2 (0.31%)
0    1    1 (0.15%)
19   1    1 (0.15%)

统计 G2 列:
      n         n (%)
G2
11  103  103 (15.87%)
12   86   86 (13.25%)
10   83   83 (12.79%)
13   80   80 (12.33%)
9    72   72 (11.09%)
14   54    54 (8.32%)
8    40    40 (6.16%)
15   38    38 (5.86%)
16   25    25 (3.85%)
17   20    20 (3.08%)
7    16    16 (2.47%)
18   14    14 (2.16%)
6     7     7 (1.08%)
0     7     7 (1.08%)
5     3     3 (0.46%)
19    1     1 (0.15%)

统计 G3 列:
      n         n (%)
G3
11  104  104 (16.02%)
10   97   97 (14.95%)
13   82   82 (12.63%)
12   72   72 (11.09%)
14   63    63 (9.71%)
15   49    49 (7.55%)
16   36    36 (5.55%)
9    35    35 (5.39%)
8    35    35 (5.39%)
17   29    29 (4.47%)
18   15    15 (2.31%)
0    15    15 (2.31%)
7    10    10 (1.54%)
6     3     3 (0.46%)
19    2     2 (0.31%)
1     1     1 (0.15%)
5     1     1 (0.15%)

In [13]:
df = data

# 统计每个分类特征的数量和百分比
summary = {}

# 遍历每个分类特征
for column in df.select_dtypes(include=['object', 'int64']).columns:
    counts = df[column].value_counts()  # 计算每个标签的数量
    percentages = df[column].value_counts(normalize=True) * 100  # 计算每个标签的百分比
    
    # 格式化输出每个特征的统计数据
    summary[column] = pd.DataFrame({
        'n': counts,
        'n (%)': counts.astype(str) + ' (' + percentages.round(2).astype(str) + '%)'
    })

# 将统计结果保存到 Excel 文件
with pd.ExcelWriter('stu_sta_result.xlsx') as writer:
    for column, stats in summary.items():
        # 将每个特征的统计数据存储到不同的工作表中
        stats.to_excel(writer, sheet_name=column, index=True)

print("Excel 文件已保存。")

Excel 文件已保存。

In [10]:
len(data)

649

In [11]:
len(data.columns)

33

In [12]:
# 获取每个属性的可能取值
unique_values = {column: data[column].unique() for column in data.columns}

In [13]:
unique_values

{'school': array(['GP', 'MS'], dtype=object),
 'sex': array(['F', 'M'], dtype=object),
 'age': array([18, 17, 15, 16, 19, 22, 20, 21], dtype=int64),
 'address': array(['U', 'R'], dtype=object),
 'famsize': array(['GT3', 'LE3'], dtype=object),
 'Pstatus': array(['A', 'T'], dtype=object),
 'Medu': array([4, 1, 3, 2, 0], dtype=int64),
 'Fedu': array([4, 1, 2, 3, 0], dtype=int64),
 'Mjob': array(['at_home', 'health', 'other', 'services', 'teacher'], dtype=object),
 'Fjob': array(['teacher', 'other', 'services', 'health', 'at_home'], dtype=object),
 'reason': array(['course', 'other', 'home', 'reputation'], dtype=object),
 'guardian': array(['mother', 'father', 'other'], dtype=object),
 'traveltime': array([2, 1, 3, 4], dtype=int64),
 'studytime': array([2, 3, 1, 4], dtype=int64),
 'failures': array([0, 3, 1, 2], dtype=int64),
 'schoolsup': array(['yes', 'no'], dtype=object),
 'famsup': array(['no', 'yes'], dtype=object),
 'paid': array(['no', 'yes'], dtype=object),
 'activities': array(['no', 'yes'], dtype=object),
 'nursery': array(['yes', 'no'], dtype=object),
 'higher': array(['yes', 'no'], dtype=object),
 'internet': array(['no', 'yes'], dtype=object),
 'romantic': array(['no', 'yes'], dtype=object),
 'famrel': array([4, 5, 3, 1, 2], dtype=int64),
 'freetime': array([3, 2, 4, 1, 5], dtype=int64),
 'goout': array([4, 3, 2, 1, 5], dtype=int64),
 'Dalc': array([1, 2, 5, 3, 4], dtype=int64),
 'Walc': array([1, 3, 2, 4, 5], dtype=int64),
 'health': array([3, 5, 1, 2, 4], dtype=int64),
 'absences': array([ 4,  2,  6,  0, 10,  8, 16, 14,  1, 12, 24, 22, 32, 30, 21, 15,  9,
        18, 26,  7, 11,  5, 13,  3], dtype=int64),
 'G1': array([ 0,  9, 12, 14, 11, 13, 10, 15, 17,  8, 16, 18,  7,  6,  5,  4, 19],
       dtype=int64),
 'G2': array([11, 13, 14, 12, 16, 17,  8, 10, 15,  9,  7,  6, 18, 19,  0,  5],
       dtype=int64),
 'G3': array([11, 12, 14, 13, 17, 15,  7, 10, 16,  9,  8, 18,  6,  0,  1,  5, 19],
       dtype=int64)}

In [14]:
data.isna().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [15]:
# 数据预处理
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [16]:
# 初始化标签编码器和独热编码器

# 二元属性使用标签编码，多个类别的属性使用独热编码

label_encoder = LabelEncoder()

onehot_encoder = OneHotEncoder(sparse=False, drop='first')  # drop='first' 以避免多重共线性

In [17]:
# 选择需要标签编码的列 (二元属性)
binary_columns = ['schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic']

# 性别属性是敏感属性，不做处理

# 对二元属性列应用标签编码    
for column in binary_columns:
    data[column + '_encoded'] = label_encoder.fit_transform(data[column]).astype('int64')

In [18]:
# 选择需要独热编码的其他object类型的列
other_object_columns = ['school', 'address', 'famsize', 'Pstatus', 'reason', 'guardian','Mjob', 'Fjob']

# 对这些列应用独热编码并合并到原始DataFrame中
for column in other_object_columns:
    dummies = pd.get_dummies(data[column], prefix=column, drop_first=True).astype(int)
    data = pd.concat([data, dummies.astype('int64')], axis=1)

In [19]:
# 检查一下新增加的列
new_columns = [col for col in data.columns if '_encoded' in col or any(col.startswith(prefix) for prefix in other_object_columns)]

In [20]:
data[new_columns].head()

,school,address,famsize,Pstatus,Mjob,Fjob,reason,guardian,schoolsup,schoolsup_encoded,famsup_encoded,paid_encoded,activities_encoded,nursery_encoded,higher_encoded,internet_encoded,romantic_encoded,school_MS,address_U,famsize_LE3,Pstatus_T,reason_home,reason_other,reason_reputation,guardian_mother,guardian_other,Mjob_health,Mjob_other,Mjob_services,Mjob_teacher,Fjob_health,Fjob_other,Fjob_services,Fjob_teacher
0,GP,U,GT3,A,at_home,teacher,course,mother,yes,1,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
1,GP,U,GT3,T,at_home,other,course,father,no,0,1,0,0,0,1,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0
2,GP,U,LE3,T,at_home,other,other,mother,yes,1,0,0,0,1,1,1,0,0,1,1,1,0,1,0,1,0,0,0,0,0,0,1,0,0
3,GP,U,GT3,T,health,services,home,mother,no,0,1,0,1,1,1,1,1,0,1,0,1,1,0,0,1,0,1,0,0,0,0,0,1,0
4,GP,U,GT3,T,other,other,home,father,no,0,1,0,0,1,1,0,0,0,1,0,1,1,0,0,0,0,0,1,0,0,0,1,0,0

In [21]:
data.head(20)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,...,schoolsup_encoded,famsup_encoded,paid_encoded,activities_encoded,nursery_encoded,higher_encoded,internet_encoded,romantic_encoded,school_MS,address_U,famsize_LE3,Pstatus_T,reason_home,reason_other,reason_reputation,guardian_mother,guardian_other,Mjob_health,Mjob_other,Mjob_services,Mjob_teacher,Fjob_health,Fjob_other,Fjob_services,Fjob_teacher
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother,2,2,0,yes,no,no,no,yes,yes,no,no,4,3,...,1,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father,1,2,0,no,yes,no,no,no,yes,yes,no,5,3,...,0,1,0,0,0,1,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother,1,2,0,yes,no,no,no,yes,yes,yes,no,4,3,...,1,0,0,0,1,1,1,0,0,1,1,1,0,1,0,1,0,0,0,0,0,0,1,0,0
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother,1,3,0,no,yes,no,yes,yes,yes,yes,yes,3,2,...,0,1,0,1,1,1,1,1,0,1,0,1,1,0,0,1,0,1,0,0,0,0,0,1,0
4,GP,F,16,U,GT3,T,3,3,other,other,home,father,1,2,0,no,yes,no,no,yes,yes,no,no,4,3,...,0,1,0,0,1,1,0,0,0,1,0,1,1,0,0,0,0,0,1,0,0,0,1,0,0
5,GP,M,16,U,LE3,T,4,3,services,other,reputation,mother,1,2,0,no,yes,no,yes,yes,yes,yes,no,5,4,...,0,1,0,1,1,1,1,0,0,1,1,1,0,0,1,1,0,0,0,1,0,0,1,0,0
6,GP,M,16,U,LE3,T,2,2,other,other,home,mother,1,2,0,no,no,no,no,yes,yes,yes,no,4,4,...,0,0,0,0,1,1,1,0,0,1,1,1,1,0,0,1,0,0,1,0,0,0,1,0,0
7,GP,F,17,U,GT3,A,4,4,other,teacher,home,mother,2,2,0,yes,yes,no,no,yes,yes,no,no,4,1,...,1,1,0,0,1,1,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1
8,GP,M,15,U,LE3,A,3,2,services,other,home,mother,1,2,0,no,yes,no,no,yes,yes,yes,no,4,2,...,0,1,0,0,1,1,1,0,0,1,1,0,1,0,0,1,0,0,0,1,0,0,1,0,0
9,GP,M,15,U,GT3,T,3,4,other,other,home,mother,1,2,0,no,yes,no,yes,yes,yes,yes,no,5,5,...,0,1,0,1,1,1,1,0,0,1,0,1,1,0,0,1,0,0,1,0,0,0,1,0,0
10,GP,F,15,U,GT3,T,4,4,teacher,health,reputation,mother,1,2,0,no,yes,no,no,yes,yes,yes,no,3,3,...,0,1,0,0,1,1,1,0,0,1,0,1,0,0,1,1,0,0,0,0,1,1,0,0,0
11,GP,F,15,U,GT3,T,2,1,services,other,reputation,father,3,3,0,no,yes,no,yes,yes,yes,yes,no,5,2,...,0,1,0,1,1,1,1,0,0,1,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0
12,GP,M,15,U,LE3,T,4,4,health,services,course,father,1,1,0,no,yes,no,yes,yes,yes,yes,no,4,3,...,0,1,0,1,1,1,1,0,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,1,0
13,GP,M,15,U,GT3,T,4,3,teacher,other,course,mother,2,2,0,no,yes,no,no,yes,yes,yes,no,5,4,...,0,1,0,0,1,1,1,0,0,1,0,1,0,0,0,1,0,0,0,0,1,0,1,0,0
14,GP,M,15,U,GT3,A,2,2,other,other,home,other,1,3,0,no,yes,no,no,yes,yes,yes,yes,4,5,...,0,1,0,0,1,1,1,1,0,1,0,0,1,0,0,0,1,0,1,0,0,0,1,0,0
15,GP,F,16,U,GT3,T,4,4,health,other,home,mother,1,1,0,no,yes,no,no,yes,yes,yes,no,4,4,...,0,1,0,0,1,1,1,0,0,1,0,1,1,0,0,1,0,1,0,0,0,0,1,0,0
16,GP,F,16,U,GT3,T,4,4,services,services,reputation,mother,1,3,0,no,yes,no,yes,yes,yes,yes,no,3,2,...,0,1,0,1,1,1,1,0,0,1,0,1,0,0,1,1,0,0,0,1,0,0,0,1,0
17,GP,F,16,U,GT3,T,3,3,other,other,reputation,mother,3,2,0,yes,yes,no,yes,yes,yes,no,no,5,3,...,1,1,0,1,1,1,0,0,0,1,0,1,0,0,1,1,0,0,1,0,0,0,1,0,0
18,GP,M,17,U,GT3,T,3,2,services,services,course,mother,1,1,3,no,yes,yes,yes,yes,yes,yes,no,5,5,...,0,1,1,1,1,1,1,0,0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0
19,GP,M,16,U,LE3,T,4,3,health,other,home,father,1,1,0,no,no,no,yes,yes,yes,yes,no,3,1,...,0,0,0,1,1,1,1,0,0,1,1,1,1,0,0,0,0,1,0,0,0,0,1,0,0

In [22]:
# 获取每个属性的可能取值
unique_values_encoded = {column: data[column].unique() for column in data.columns}

In [23]:
unique_values_encoded

{'school': array(['GP', 'MS'], dtype=object),
 'sex': array(['F', 'M'], dtype=object),
 'age': array([18, 17, 15, 16, 19, 22, 20, 21], dtype=int64),
 'address': array(['U', 'R'], dtype=object),
 'famsize': array(['GT3', 'LE3'], dtype=object),
 'Pstatus': array(['A', 'T'], dtype=object),
 'Medu': array([4, 1, 3, 2, 0], dtype=int64),
 'Fedu': array([4, 1, 2, 3, 0], dtype=int64),
 'Mjob': array(['at_home', 'health', 'other', 'services', 'teacher'], dtype=object),
 'Fjob': array(['teacher', 'other', 'services', 'health', 'at_home'], dtype=object),
 'reason': array(['course', 'other', 'home', 'reputation'], dtype=object),
 'guardian': array(['mother', 'father', 'other'], dtype=object),
 'traveltime': array([2, 1, 3, 4], dtype=int64),
 'studytime': array([2, 3, 1, 4], dtype=int64),
 'failures': array([0, 3, 1, 2], dtype=int64),
 'schoolsup': array(['yes', 'no'], dtype=object),
 'famsup': array(['no', 'yes'], dtype=object),
 'paid': array(['no', 'yes'], dtype=object),
 'activities': array(['no', 'yes'], dtype=object),
 'nursery': array(['yes', 'no'], dtype=object),
 'higher': array(['yes', 'no'], dtype=object),
 'internet': array(['no', 'yes'], dtype=object),
 'romantic': array(['no', 'yes'], dtype=object),
 'famrel': array([4, 5, 3, 1, 2], dtype=int64),
 'freetime': array([3, 2, 4, 1, 5], dtype=int64),
 'goout': array([4, 3, 2, 1, 5], dtype=int64),
 'Dalc': array([1, 2, 5, 3, 4], dtype=int64),
 'Walc': array([1, 3, 2, 4, 5], dtype=int64),
 'health': array([3, 5, 1, 2, 4], dtype=int64),
 'absences': array([ 4,  2,  6,  0, 10,  8, 16, 14,  1, 12, 24, 22, 32, 30, 21, 15,  9,
        18, 26,  7, 11,  5, 13,  3], dtype=int64),
 'G1': array([ 0,  9, 12, 14, 11, 13, 10, 15, 17,  8, 16, 18,  7,  6,  5,  4, 19],
       dtype=int64),
 'G2': array([11, 13, 14, 12, 16, 17,  8, 10, 15,  9,  7,  6, 18, 19,  0,  5],
       dtype=int64),
 'G3': array([11, 12, 14, 13, 17, 15,  7, 10, 16,  9,  8, 18,  6,  0,  1,  5, 19],
       dtype=int64),
 'schoolsup_encoded': array([1, 0], dtype=int64),
 'famsup_encoded': array([0, 1], dtype=int64),
 'paid_encoded': array([0, 1], dtype=int64),
 'activities_encoded': array([0, 1], dtype=int64),
 'nursery_encoded': array([1, 0], dtype=int64),
 'higher_encoded': array([1, 0], dtype=int64),
 'internet_encoded': array([0, 1], dtype=int64),
 'romantic_encoded': array([0, 1], dtype=int64),
 'school_MS': array([0, 1], dtype=int64),
 'address_U': array([1, 0], dtype=int64),
 'famsize_LE3': array([0, 1], dtype=int64),
 'Pstatus_T': array([0, 1], dtype=int64),
 'reason_home': array([0, 1], dtype=int64),
 'reason_other': array([0, 1], dtype=int64),
 'reason_reputation': array([0, 1], dtype=int64),
 'guardian_mother': array([1, 0], dtype=int64),
 'guardian_other': array([0, 1], dtype=int64),
 'Mjob_health': array([0, 1], dtype=int64),
 'Mjob_other': array([0, 1], dtype=int64),
 'Mjob_services': array([0, 1], dtype=int64),
 'Mjob_teacher': array([0, 1], dtype=int64),
 'Fjob_health': array([0, 1], dtype=int64),
 'Fjob_other': array([0, 1], dtype=int64),
 'Fjob_services': array([0, 1], dtype=int64),
 'Fjob_teacher': array([1, 0], dtype=int64)}

In [24]:
data['G3_prediction'] = data['G3'].apply(lambda x: '1' if x >= 12 else '0').astype('int64')

In [25]:
data = data.drop(columns=['school','address','famsize', 'Pstatus','Mjob','Fjob','reason', 'guardian']).reset_index(drop=True)

In [26]:
data = data.drop(columns=['schoolsup', 'famsup','paid', 'activities', 'nursery', 'higher', 'internet', 'romantic','G3']).reset_index(drop=True)

In [27]:
data['sex'] = data['sex'].apply(lambda x: 1 if x == "F" else 0)

In [28]:
data.head(20)

,sex,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,schoolsup_encoded,famsup_encoded,paid_encoded,activities_encoded,nursery_encoded,higher_encoded,internet_encoded,romantic_encoded,school_MS,address_U,famsize_LE3,Pstatus_T,reason_home,reason_other,reason_reputation,guardian_mother,guardian_other,Mjob_health,Mjob_other,Mjob_services,Mjob_teacher,Fjob_health,Fjob_other,Fjob_services,Fjob_teacher,G3_prediction
0,1,18,4,4,2,2,0,4,3,4,1,1,3,4,0,11,1,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
1,1,17,1,1,1,2,0,5,3,3,1,1,3,2,9,11,0,1,0,0,0,1,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,1,15,1,1,1,2,0,4,3,2,2,3,3,6,12,13,1,0,0,0,1,1,1,0,0,1,1,1,0,1,0,1,0,0,0,0,0,0,1,0,0,1
3,1,15,4,2,1,3,0,3,2,2,1,1,5,0,14,14,0,1,0,1,1,1,1,1,0,1,0,1,1,0,0,1,0,1,0,0,0,0,0,1,0,1
4,1,16,3,3,1,2,0,4,3,2,1,2,5,0,11,13,0,1,0,0,1,1,0,0,0,1,0,1,1,0,0,0,0,0,1,0,0,0,1,0,0,1
5,0,16,4,3,1,2,0,5,4,2,1,2,5,6,12,12,0,1,0,1,1,1,1,0,0,1,1,1,0,0,1,1,0,0,0,1,0,0,1,0,0,1
6,0,16,2,2,1,2,0,4,4,4,1,1,3,0,13,12,0,0,0,0,1,1,1,0,0,1,1,1,1,0,0,1,0,0,1,0,0,0,1,0,0,1
7,1,17,4,4,2,2,0,4,1,4,1,1,1,2,10,13,1,1,0,0,1,1,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,1
8,0,15,3,2,1,2,0,4,2,2,1,1,1,0,15,16,0,1,0,0,1,1,1,0,0,1,1,0,1,0,0,1,0,0,0,1,0,0,1,0,0,1
9,0,15,3,4,1,2,0,5,5,1,1,1,5,0,12,12,0,1,0,1,1,1,1,0,0,1,0,1,1,0,0,1,0,0,1,0,0,0,1,0,0,1
10,1,15,4,4,1,2,0,3,3,3,1,2,2,2,14,14,0,1,0,0,1,1,1,0,0,1,0,1,0,0,1,1,0,0,0,0,1,1,0,0,0,1
11,1,15,2,1,3,3,0,5,2,2,1,1,4,0,10,12,0,1,0,1,1,1,1,0,0,1,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,1
12,0,15,4,4,1,1,0,4,3,3,1,3,5,0,12,13,0,1,0,1,1,1,1,0,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,1,0,1
13,0,15,4,3,2,2,0,5,4,3,1,2,3,0,12,12,0,1,0,0,1,1,1,0,0,1,0,1,0,0,0,1,0,0,0,0,1,0,1,0,0,1
14,0,15,2,2,1,3,0,4,5,2,1,1,3,0,14,14,0,1,0,0,1,1,1,1,0,1,0,0,1,0,0,0,1,0,1,0,0,0,1,0,0,1
15,1,16,4,4,1,1,0,4,4,4,1,2,2,6,17,17,0,1,0,0,1,1,1,0,0,1,0,1,1,0,0,1,0,1,0,0,0,0,1,0,0,1
16,1,16,4,4,1,3,0,3,2,3,1,2,2,10,13,13,0,1,0,1,1,1,1,0,0,1,0,1,0,0,1,1,0,0,0,1,0,0,0,1,0,1
17,1,16,3,3,3,2,0,5,3,2,1,1,4,2,13,14,1,1,0,1,1,1,0,0,0,1,0,1,0,0,1,1,0,0,1,0,0,0,1,0,0,1
18,0,17,3,2,1,1,3,5,5,5,2,4,5,2,8,8,0,1,1,1,1,1,1,0,0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0
19,0,16,4,3,1,1,0,3,1,3,1,3,5,6,12,12,0,0,0,1,1,1,1,0,0,1,1,1,1,0,0,0,0,1,0,0,0,0,1,0,0,1

In [29]:
data.to_csv('./stuper_pre.csv')

In [30]:
data.isna().sum()

sex                   0
age                   0
Medu                  0
Fedu                  0
traveltime            0
studytime             0
failures              0
famrel                0
freetime              0
goout                 0
Dalc                  0
Walc                  0
health                0
absences              0
G1                    0
G2                    0
schoolsup_encoded     0
famsup_encoded        0
paid_encoded          0
activities_encoded    0
nursery_encoded       0
higher_encoded        0
internet_encoded      0
romantic_encoded      0
school_MS             0
address_U             0
famsize_LE3           0
Pstatus_T             0
reason_home           0
reason_other          0
reason_reputation     0
guardian_mother       0
guardian_other        0
Mjob_health           0
Mjob_other            0
Mjob_services         0
Mjob_teacher          0
Fjob_health           0
Fjob_other            0
Fjob_services         0
Fjob_teacher          0
G3_prediction         0
dtype: int64

In [31]:
column = data.columns

column

Index(['sex', 'age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures',
       'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences',
       'G1', 'G2', 'schoolsup_encoded', 'famsup_encoded', 'paid_encoded',
       'activities_encoded', 'nursery_encoded', 'higher_encoded',
       'internet_encoded', 'romantic_encoded', 'school_MS', 'address_U',
       'famsize_LE3', 'Pstatus_T', 'reason_home', 'reason_other',
       'reason_reputation', 'guardian_mother', 'guardian_other', 'Mjob_health',
       'Mjob_other', 'Mjob_services', 'Mjob_teacher', 'Fjob_health',
       'Fjob_other', 'Fjob_services', 'Fjob_teacher', 'G3_prediction'],
      dtype='object')

In [32]:
# 获取每个属性的可能取值
unique_values_encoded = {column: data[column].unique() for column in data.columns}

unique_values_encoded

{'sex': array([1, 0], dtype=int64),
 'age': array([18, 17, 15, 16, 19, 22, 20, 21], dtype=int64),
 'Medu': array([4, 1, 3, 2, 0], dtype=int64),
 'Fedu': array([4, 1, 2, 3, 0], dtype=int64),
 'traveltime': array([2, 1, 3, 4], dtype=int64),
 'studytime': array([2, 3, 1, 4], dtype=int64),
 'failures': array([0, 3, 1, 2], dtype=int64),
 'famrel': array([4, 5, 3, 1, 2], dtype=int64),
 'freetime': array([3, 2, 4, 1, 5], dtype=int64),
 'goout': array([4, 3, 2, 1, 5], dtype=int64),
 'Dalc': array([1, 2, 5, 3, 4], dtype=int64),
 'Walc': array([1, 3, 2, 4, 5], dtype=int64),
 'health': array([3, 5, 1, 2, 4], dtype=int64),
 'absences': array([ 4,  2,  6,  0, 10,  8, 16, 14,  1, 12, 24, 22, 32, 30, 21, 15,  9,
        18, 26,  7, 11,  5, 13,  3], dtype=int64),
 'G1': array([ 0,  9, 12, 14, 11, 13, 10, 15, 17,  8, 16, 18,  7,  6,  5,  4, 19],
       dtype=int64),
 'G2': array([11, 13, 14, 12, 16, 17,  8, 10, 15,  9,  7,  6, 18, 19,  0,  5],
       dtype=int64),
 'schoolsup_encoded': array([1, 0], dtype=int64),
 'famsup_encoded': array([0, 1], dtype=int64),
 'paid_encoded': array([0, 1], dtype=int64),
 'activities_encoded': array([0, 1], dtype=int64),
 'nursery_encoded': array([1, 0], dtype=int64),
 'higher_encoded': array([1, 0], dtype=int64),
 'internet_encoded': array([0, 1], dtype=int64),
 'romantic_encoded': array([0, 1], dtype=int64),
 'school_MS': array([0, 1], dtype=int64),
 'address_U': array([1, 0], dtype=int64),
 'famsize_LE3': array([0, 1], dtype=int64),
 'Pstatus_T': array([0, 1], dtype=int64),
 'reason_home': array([0, 1], dtype=int64),
 'reason_other': array([0, 1], dtype=int64),
 'reason_reputation': array([0, 1], dtype=int64),
 'guardian_mother': array([1, 0], dtype=int64),
 'guardian_other': array([0, 1], dtype=int64),
 'Mjob_health': array([0, 1], dtype=int64),
 'Mjob_other': array([0, 1], dtype=int64),
 'Mjob_services': array([0, 1], dtype=int64),
 'Mjob_teacher': array([0, 1], dtype=int64),
 'Fjob_health': array([0, 1], dtype=int64),
 'Fjob_other': array([0, 1], dtype=int64),
 'Fjob_services': array([0, 1], dtype=int64),
 'Fjob_teacher': array([1, 0], dtype=int64),
 'G3_prediction': array([0, 1], dtype=int64)}

In [33]:
len(data.columns)

42